# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-24 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('profile_photo', models.ImageField(blank=True, upload_to='profile_photos/')),
                ('user_profile_photo', models.IntegerField(default=0)),
            ],
        ),
    ]
