# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
