# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_profile_photo',
        ),
    ]
